name: Hexo Build and Deploy

on: 
  push:
    branches: source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ericzyh/github-actions-hexo@master
        with:
          deploykey: ${{secrets.ACTIONS_DEPLOY_KEY }}
          username: zhaoyuhao
          email: 8040334@qq.com
